title: "Tiralabra - 2022 periodi 2"
entitle: "Data Structures Lab, 2022 period 2"
email: ''
description: "Helsingin yliopiston Aineopintojen harjoitusty√∂: Tietorakenteet ja algoritmit - kurssin kurssisivu"
endescription: "Course page for the Data Structures Project course at the University of Helsinki"
baseurl: '/2022_p2' # the subpath of your site, e.g. /blog
url: https://tiralabra.github.io/2022_p2/ # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true

collections:
  fi:
    output: true
  en:
    output: true
